#!/bin/sh
qemu-system-x86_64 \
    -enable-kvm \
    -m 8192 \
    -cpu host,kvm=off \
    -smp 3,sockets=1,cores=3,threads=1 \
    -drive if=pflash,format=raw,readonly,file=OVMF.fd \
    -device vfio-pci,host=01:00.0 \
    -device vfio-pci,host=01:00.1 \
    -device vfio-pci,host=04:00.0 \
    -netdev tap,id=net0,script=./qemu-ifup,downscript=./qemu-ifdown \
    -device virtio-net-pci,netdev=net0 \
    -vga none \
    -drive file=win10.raw,format=raw,cache=none,if=ide,index=0 \
    -nographic \
    -usb \
    -device usb-host,vendorid=0x046d,productid=0xc05a \
    -device usb-host,vendorid=0x045e,productid=0x00db \
    -device nec-usb-xhci,id=xhci \
    -device usb-host,vendorid=0x0781,productid=0x5580,bus=xhci.0

