#!/bin/sh
PCI_DEV=/sys/bus/pci/devices
NEW_ID=/sys/bus/pci/drivers/vfio-pci/new_id
echo 0000:01:00.0 > $PCI_DEV/0000:01:00.0/driver/unbind
echo 0000:01:00.1 > $PCI_DEV/0000:01:00.1/driver/unbind
echo 0000:02:00.0 > $PCI_DEV/0000:02:00.0/driver/unbind
echo 0000:04:00.0 > $PCI_DEV/0000:04:00.0/driver/unbind
echo "10de 13c0" > $NEW_ID
echo "10de 0fbb" > $NEW_ID
echo "bdbd a130" > $NEW_ID
echo "1106 3403" > $NEW_ID

